[versions]
agp = "9.0.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
fragment = "1.8.9"
material = "1.14.0-alpha09"
ketch = "2.0.6"
room = "2.8.4"
ksp = "2.3.5"
retrofit = "3.0.0"
converterGson = "3.0.0"
constraintlayout = "2.2.1"
recyclerview = "1.4.0"
okhttp = "5.3.2"
rxjava = "2.2.21"
rxjava-adapter = "2.12.0"
rxandroid = "2.1.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

ketch = { group = "com.github.khushpanchal", name = "Ketch", version.ref = "ketch" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

squareup-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
squareup-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
squareup-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "converterGson" }

rxjava2 = { group = "io.reactivex.rxjava2", name = "rxjava", version.ref = "rxjava" }
rxjava2-rxandroid = { group = "io.reactivex.rxjava2", name = "rxandroid", version.ref = "rxandroid" }
rxjava2-room = { group = "androidx.room", name = "room-rxjava2", version.ref = "rxjava" }
rxjava2-adapter = { group = "com.squareup.retrofit2", name = "adapter-rxjava2", version.ref = "rxjava-adapter" }

androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
